stages:
  - test
  - build
  - deployment

license-header:
  stage: test
  image: alpine
  script:
  - './.gitlab/licenseHeaderCheck.sh ./.gitlab/license/LICENSE_HEADER'

file-naming:
  stage: test
  image: alpine
  script:
  - 'apk update && apk add bash'
  - './.gitlab/fileNamingConventionCheck.sh'

global-logging:
  stage: test
  image: alpine
  script:
  - 'apk update && apk add grep'
  - './.gitlab/scrambleLoggingCheck.sh'

desktop-clients:
  stage: build
  image: mrminimal/godot-desktop-export:3.1.0
  script:
    - 'mkdir -p export/server/linux'
    - 'mkdir -p export/server/mac'
    - 'mkdir -p export/server/window'
    - 'cd Scramble-client'
    - 'godot -v --export "Linux" ../export/client/linux/Scramble-client.x64'
    - 'godot -v --export "Mac" ../export/client/mac/Scramble-client.x64'
    - 'godot -v --export "Windows" ../export/client/windows/Scramble-client.exe'
  artifacts:
    name: Scramble-client-$CI_BUILD_REF
    paths:
      - export/client

desktop-servers:
  stage: build
  image: mrminimal/godot-desktop-export:3.1.0
  script:
    - 'mkdir -p export/server/linux'
    - 'mkdir -p export/server/mac'
    - 'mkdir -p export/server/window'
    - 'cd Scramble-server'
    - 'godot -v --export "Linux" ../export/server/linux/Scramble-server.x64'
    - 'godot -v --export "Mac" ../export/server/mac/Scramble-server.x64'
    - 'godot -v --export "Windows" ../export/server/windows/Scramble-server.exe'
  artifacts:
    name: Scramble-server-$CI_BUILD_REF
    paths:
      - export/server
