stages:
  - test
  - build
  - deploy

license-header:
  stage: test
  image: alpine
  script:
  - '.gitlab/licenseHeaderCheck.sh .gitlab/license/LICENSE_HEADER'

file-naming:
  stage: test
  image: alpine
  script:
  - 'apk update && apk add bash'
  - './.gitlab/fileNamingConventionCheck.sh'

global-logging:
  stage: test
  image: alpine
  script:
  - 'apk update && apk add grep'
  - './.gitlab/scrambleLoggingCheck.sh'

.template_export: &template_export
  stage: build
  image: mrminimal/godot-desktop-export:3.1.1
  script:
    - mkdir -p export/$TYPE/$PLATFORM
    - cd Scramble-$TYPE
    - godot -v --export "$PLATFORM"   ../export/$TYPE/$PLATFORM/Scramble-$TYPE.x64
    - if ! test -f export/$TYPE/$PLATFORM/Scramble-$TYPE.x64; then exit 1; fi
  artifacts:
    name: Scramble-$TYPE-$CI_BUILD_REF
    paths:
      - export/$TYPE

desktop-client-linux:
  <<: *template_export
  variables:
    TYPE: "client"
    PLATFORM: "linux"


desktop-server-linux:
  <<: *template_export
  variables:
    TYPE: "server"
    PLATFORM: "linux"


desktop-client-mac:
  <<: *template_export
  variables:
    TYPE: "client"
    PLATFORM: "mac"


desktop-server-mac:
  <<: *template_export
  variables:
    TYPE: "server"
    PLATFORM: "mac"


desktop-client-windows:
  <<: *template_export
  variables:
    TYPE: "client"
    PLATFORM: "windows"


desktop-server-windows:
  <<: *template_export
  variables:
    TYPE: "server"
    PLATFORM: "windows"

