stages:
  - test
  - build
  - deploy

# ---------- Templates -------------

.template_export: &template_export
  stage: build
  image: mrminimal/godot-desktop-export:3.1.1
  script:
    - mkdir -p export
    - cd Scramble-$TYPE
    - godot -v --export $PLATFORM ../export/Scramble-$TYPE.$EXTENSION
    - if ! test -f ../export/Scramble-$TYPE.$EXTENSION; then exit 1; fi
  artifacts:
    name: Scramble-$TYPE-$CI_BUILD_REF
    paths:
      - export

# -------------- Jobs --------------

license-header:
  stage: test
  image: alpine
  script:
  - .gitlab/licenseHeaderCheck.sh .gitlab/license/LICENSE_HEADER

file-naming:
  stage: test
  image: alpine
  script:
  - apk update && apk add bash
  - ./.gitlab/fileNamingConventionCheck.sh

global-logging:
  stage: test
  image: alpine
  script:
  - apk update && apk add grep
  - ./.gitlab/scrambleLoggingCheck.sh

# Client

linux-client:
  <<: *template_export
  variables:
    TYPE: "client"
    PLATFORM: "linux"
    EXTENSION: "x64"

mac-client:
  <<: *template_export
  variables:
    TYPE: "client"
    PLATFORM: "mac"
    EXTENSION: "x64"

windows-client:
  <<: *template_export
  variables:
    TYPE: "client"
    PLATFORM: "windows"
    EXTENSION: "exe"

# Server

linux-server:
  <<: *template_export
  variables:
    TYPE: "server"
    PLATFORM: "linux"
    EXTENSION: "x64"

mac-server:
  <<: *template_export
  variables:
    TYPE: "server"
    PLATFORM: "mac"
    EXTENSION: "x64"

windows-server:
  <<: *template_export
  variables:
    TYPE: "server"
    PLATFORM: "windows"
    EXTENSION: "exe"

